### PR TITLE
Mixed Frontend & Backend

### PR DESCRIPTION
**Pull request by jaideep1163**
### Mixed Frontend & Backend

I mixed the ***Backend*** and ***frontend*** Please Check if It Works Good In Windows And Linux

Works Well In ***MacOS***

Thanks ,
Jaideep

### CODE REVIEW

**Comment by Karthik2008** [comment]
Cool,
The Terminal is not working in mac for me...

will test in windows and give a comment,
as soon as I can

**Comment by jaideep1163** [comment]
Ok,

Great

**Comment by Karthik2008** [comment]
if we type "Terminal" in windows, it says "related to terminal" and opens "CMD"

**Comment by jaideep1163** [comment]
***Thats Great***

**Comment by jaideep1163** [comment]
***Can You Please Approve My Pull Request***

Thanks,
    ###Jaideep

**Comment by Karthik2008** [comment]
Cool,

Approved

**Pull request closed without merging**
